name: Main

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.5.4, 0.6.0]

    steps:
    - uses: actions/checkout@v2
    - run: ./bench.sh ${{ matrix.version }}
